### ISSUE TITLE
One or more undefined variables: 'unicode object' has no attribute 'name'

### ISSUE THREAD

**Issue by sebastianwr** [pmarkham/ansible-adobe-aem#3]
When executing the `aem_packages_common` role, the definition of `packages_common` and the usage in the task don't match.

It looks like the task expects something like this:

``` yaml
packages_common:
  - { name: "my-package-1.0", file: "my-package-1.0.zip" }
  - ...
```

whereas the sample (and in my config) they are defined simply as this:

``` yaml
packages_common:
  - aem-5.6.1-service-pack-2-1.0.zip
```

This results in the following error when executing the playbook:

```
TASK: [aem_packages_common | Upload common packages] ************************** 
fatal: [xx.xx.xx.xx] => One or more undefined variables: 'unicode object' has no attribute 'name'
...
```

**Comment by pmarkham** [comment]
I did change the module at some stage, it looks like I forgot to update the sample to match. I'll fix it and push a new version.

You need to specify `name` at a minimum; if the file name doesn't match the package name, you also need to specify `file`. So, something like this:

```
packages_common:
    # package name and file name the same
    - name: 'cq-6.0.0-hotfix-5869-1.0.2.zip'
    # package name and file name different
    - name: 'cq-6.0.0-hotfix-5918-wrapper-1.6.zip'
      file: 'cq-6.0.0-hotfix-5918-1.6.zip'
```

Thanks for the feedback.
